# GENERATED by regenerate.sh — do not hand-edit.
{ fetchers }:

fetchers.fetchdocker {
  name = "halogen-flash-server";
  registry = "https://ghcr.io/v2/";
  repository = "richermans";
  imageName = "halogen-flash-server";
  tag = "0.5.6";
  imageConfig = fetchers.fetchDockerConfig {
    registry = "https://ghcr.io/v2/";
    repository = "richermans";
    imageName = "halogen-flash-server";
    tag = "0.5.6";
    configDigest = "51f4dc9636ed2ffeeae36e503825d249fb48919e312cc609d3b862f22cadab4f";
    sha256 = "0kxbmlng4qmqsc4wcb1iks8liys9s8jkhl3fwgmgwbzd6sbdrx2i";
  };
  imageLayers = [
    (fetchers.fetchDockerLayer {
      registry = "https://ghcr.io/v2/";
      repository = "richermans";
      imageName = "halogen-flash-server";
      tag = "0.5.6";
      layerDigest = "sha256:0e2832628b6b794f0684baf252d2d78b88e011a6f24c0532b86ba495c6b8e82c";
      sha256 = "0b78p339b93bp0r0ak7jlq8y124bsz955wmshh34yybbidi34a0f";
    })
    (fetchers.fetchDockerLayer {
      registry = "https://ghcr.io/v2/";
      repository = "richermans";
      imageName = "halogen-flash-server";
      tag = "0.5.6";
      layerDigest = "sha256:dc74e225880b25d8b37e0304815c5800addc8dcdba6e995052a43cd5dacf9ff3";
      sha256 = "1wwzrzddag54a989jvmsrn6xrb80b1f82103gsrxh98bi0jy4x6w";
    })
    (fetchers.fetchDockerLayer {
      registry = "https://ghcr.io/v2/";
      repository = "richermans";
      imageName = "halogen-flash-server";
      tag = "0.5.6";
      layerDigest = "sha256:37a4be8a8e0e6fb5336555de0e7073d2319d2eb05640c89caea5e26b467ebf07";
      sha256 = "01xzgr36pqm5msfchh2nn0p9scfjfdq0xpjmclrvavqfis5bx91p";
    })
    (fetchers.fetchDockerLayer {
      registry = "https://ghcr.io/v2/";
      repository = "richermans";
      imageName = "halogen-flash-server";
      tag = "0.5.6";
      layerDigest = "sha256:630d590a09733678664db56fcd6001e541d5e26affde895ce9e21b87dfadcb09";
      sha256 = "02fbmpgqf6z2x5f8kppzdbidahg505hcsvxm9mk7hdkk1455j3b3";
    })
    (fetchers.fetchDockerLayer {
      registry = "https://ghcr.io/v2/";
      repository = "richermans";
      imageName = "halogen-flash-server";
      tag = "0.5.6";
      layerDigest = "sha256:27ff66b637ae0187fffee59304271aa468a1657c9530c7e80f7fe0e024d7a858";
      sha256 = "0n58swjf1q3z1zlcfc4mgijs2s5438kh94z5zvzqf0df6yv6dzr7";
    })
    (fetchers.fetchDockerLayer {
      registry = "https://ghcr.io/v2/";
      repository = "richermans";
      imageName = "halogen-flash-server";
      tag = "0.5.6";
      layerDigest = "sha256:b2736a7775641c3618533ba20a039d3d1754eb45200f4fe3c8dec8b6b94f1414";
      sha256 = "050l9ywvdj6yr3ily3r08pmm85rxkl1hm8ivacc3c734fmvnlwxj";
    })
    (fetchers.fetchDockerLayer {
      registry = "https://ghcr.io/v2/";
      repository = "richermans";
      imageName = "halogen-flash-server";
      tag = "0.5.6";
      layerDigest = "sha256:01aa2046434aa9217d119015546feb2039e7b65e7087f589af44a506c6a2a479";
      sha256 = "0yd4lb30d9a4my4zb1vhbsvfff90xdpm85ch25yj3aaa8d321ah1";
    })
    (fetchers.fetchDockerLayer {
      registry = "https://ghcr.io/v2/";
      repository = "richermans";
      imageName = "halogen-flash-server";
      tag = "0.5.6";
      layerDigest = "sha256:70101ce2ed9b21c2a0566867a8bdc8efca4adfc3d0745bf1586d67c416640c6e";
      sha256 = "0vhcchbc8rvdb3qmnx6hqgglmjpgr2yshrv8ashc48cvxpi1q43h";
    })
    (fetchers.fetchDockerLayer {
      registry = "https://ghcr.io/v2/";
      repository = "richermans";
      imageName = "halogen-flash-server";
      tag = "0.5.6";
      layerDigest = "sha256:bd9ddc54bea929a22b334e73e026d4136e5b73f5cc29942896c72e4ece69b13d";
      sha256 = "0gdid774wbn7jql98afcymrmnvhkshkf0wsf6cms4ad9pradr7dx";
    })
    (fetchers.fetchDockerLayer {
      registry = "https://ghcr.io/v2/";
      repository = "richermans";
      imageName = "halogen-flash-server";
      tag = "0.5.6";
      layerDigest = "sha256:6fdc5c11def11ae7d6e7d35fef288c0ac6e5fdbd9e728f5fe6a027bf11ddbb30";
      sha256 = "0c5vvl8vy9x0wrgqywlyppyybihaihlfypykwzbff6pivq8mrp3g";
    })
    (fetchers.fetchDockerLayer {
      registry = "https://ghcr.io/v2/";
      repository = "richermans";
      imageName = "halogen-flash-server";
      tag = "0.5.6";
      layerDigest = "sha256:64037724666a56a70ffde0b20a53f19aa10981216a388ebd9dee37263a2a06a2";
      sha256 = "18h658x2cdzfknyqwf3a460hk8csy59hmcp0zl7sfmkacqj7f0v4";
    })
    (fetchers.fetchDockerLayer {
      registry = "https://ghcr.io/v2/";
      repository = "richermans";
      imageName = "halogen-flash-server";
      tag = "0.5.6";
      layerDigest = "sha256:ef9b1eb49208b919932f56cc40a03d2a23fe3121c47bb7223e5afe29aefb8dba";
      sha256 = "1fldzfp2kzjs7qibfyy444qzw8ra7nh41k2n5y9ikf88jas1x6zg";
    })
    (fetchers.fetchDockerLayer {
      registry = "https://ghcr.io/v2/";
      repository = "richermans";
      imageName = "halogen-flash-server";
      tag = "0.5.6";
      layerDigest = "sha256:e8c2c624fa8f03e8a2eb3b00da09a96a2fcb3077a1fa5bd64140615e06e03ee8";
      sha256 = "1s1yw035wqa087b5pym1fwqcnbvam44xl01vxfifh0wgz8jcdhp8";
    })
    (fetchers.fetchDockerLayer {
      registry = "https://ghcr.io/v2/";
      repository = "richermans";
      imageName = "halogen-flash-server";
      tag = "0.5.6";
      layerDigest = "sha256:65e6d336558ff9c9576cd310993fc5feb7bdabecab4596e356cf520c76276b7e";
      sha256 = "0zkb4xv0qlngavircidbxjmvvdzyqlzrj46kdibwkycgalvd7rk5";
    })
    (fetchers.fetchDockerLayer {
      registry = "https://ghcr.io/v2/";
      repository = "richermans";
      imageName = "halogen-flash-server";
      tag = "0.5.6";
      layerDigest = "sha256:02d71de54cfd1a702bbe678409203c8a63f7d64a80ec43da4c549b08d3b7da96";
      sha256 = "15nsnz9hi6sl9kd47v409bbgfqwa7hh0k137pqmp06px9kjivmq2";
    })
    (fetchers.fetchDockerLayer {
      registry = "https://ghcr.io/v2/";
      repository = "richermans";
      imageName = "halogen-flash-server";
      tag = "0.5.6";
      layerDigest = "sha256:e7407e14a12284b139475a3a013c8eff4bbdb56d2b0a338439d4babfa2fdeb34";
      sha256 = "0d7bznibzfnl762362ibdnsvsjzziqy02fjs8wwv3112l4a7wh77";
    })
    (fetchers.fetchDockerLayer {
      registry = "https://ghcr.io/v2/";
      repository = "richermans";
      imageName = "halogen-flash-server";
      tag = "0.5.6";
      layerDigest = "sha256:cbbbc51b6034ff10e5a3e54d1441818a02c0d458a60c277a7d14418efee5dcd6";
      sha256 = "1mnwwpz8wh8lgmx2f356b3ac00lah50i8kg5lgji1zrlc0dwbfyb";
    })
    (fetchers.fetchDockerLayer {
      registry = "https://ghcr.io/v2/";
      repository = "richermans";
      imageName = "halogen-flash-server";
      tag = "0.5.6";
      layerDigest = "sha256:61734ca44d3c38b1886728d58bbe86c5112f2dfc50eb09c77d5c047960c33b1d";
      sha256 = "079vqdh7j12wgp3hksshzhnjy4f5hsz8pm98cy4b2f1w9nj4qwv1";
    })
    (fetchers.fetchDockerLayer {
      registry = "https://ghcr.io/v2/";
      repository = "richermans";
      imageName = "halogen-flash-server";
      tag = "0.5.6";
      layerDigest = "sha256:b65255fd39cd87a25de63d16ef1690170b49fc177eb8d47b87aaf2e80db9423f";
      sha256 = "0gs2p46yiwmahxxx9f3y2zy4j2qpj0bfy5ixwrfs51yd77ymalmn";
    })
  ];
}
