#!/usr/bin/env bash
# regenerate.sh — regenerate nix/image.nix for the current fork image.
#
# This is the docker2nix step: fetch the registry V2 manifest for
# ghcr.io/richermans/halogen-flash-server:<tag>, download each blob an
# anonymously, hash it the way nix fixed-output derivations verify, and rewrite
# nix/image.nix. Run it after a CI publish that bumped the image.
#
# Usage:
#   regenerate.sh                    # default tag 0.5.6, or read from Dockerfile
#   regenerate.sh 0.5.7              # explicit tag
#   regenerate.sh --check 0.5.6      # verify the committed pin without rewriting
set -euo pipefail

REPO="richermans/halogen-flash-server"
TAG="${2:-${1:-}}"
CHECK=0
if [ "${1:-}" = "--check" ]; then CHECK=1; TAG="${2:-}"; fi

if [ -z "$TAG" ]; then
  TAG="$(sed -n 's/^FROM ghcr.io\/peonist-ai\/halogen-flash-server://p' Dockerfile)"
fi
[ -n "$TAG" ] || { echo "regenerate: no tag (pass one or set the Dockerfile base)" >&2; exit 1; }

OUT="${HALOGEN_NIX_OUT:-nix/image.nix}"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

TOKEN="$(curl -fsSL "https://ghcr.io/token?service=ghcr.io&scope=repository:${REPO}:pull" | python3 -c 'import json,sys;print(json.load(sys.stdin)["token"])')"
export TOKEN

MANIFEST="$TMP/manifest.json"
curl -fsSL \
  -H "Authorization: Bearer $TOKEN" \
  -H "Accept: application/vnd.docker.distribution.manifest.v2+json, application/vnd.oci.image.manifest.v1+json" \
  "https://ghcr.io/v2/${REPO}/manifests/${TAG}" -o "$MANIFEST"

python3 - "$MANIFEST" "$TAG" "$REPO" "$OUT" "$TMP" "$CHECK" <<'PY'
import json, os, re, subprocess, sys
manifest_p, tag, repo, out, tmp, check = sys.argv[1:7]
m = json.load(open(manifest_p))
cfg = m["config"]["digest"].removeprefix("sha256:")
layerdigs = [l["digest"].removeprefix("sha256:") for l in m["layers"]]

# --check compares only the reference digests (the content identifiers), so it
# needs no blob downloads: if the pinned digests and tag match the registry,
# the pin is current.
if check == "1":
    old = open(out).read() if os.path.exists(out) else ""
    old_tag = re.search(r'tag = "([^"]+)"', old)
    old_cfg = re.search(r'configDigest = "([^"]+)"', old)
    old_layers = re.findall(r'layerDigest = "sha256:([^"]+)"', old)
    ok = (old_tag and old_tag.group(1) == tag and old_cfg
          and old_cfg.group(1) == cfg and old_layers == layerdigs)
    if ok:
        print(f"regenerate: {out} already matches {repo}:{tag}")
    else:
        sys.exit(f"regenerate: pin is stale for {repo}:{tag}; run regenerate.sh")
    sys.exit(0)

def nixhash(path):
    p = subprocess.run(["nix", "hash", "file", "--type", "sha256", "--base32", path],
                       capture_output=True, text=True)
    if p.returncode != 0:
        sys.exit(f"hash failed for {path}: {p.stderr}")
    return p.stdout.strip()

def fetch_hex(hexd):
    p = f"{tmp}/{hexd}"
    if not os.path.exists(p):
        subprocess.run(["curl", "-fsSL",
                        "-H", f"Authorization: Bearer {os.environ['TOKEN']}",
                        f"https://ghcr.io/v2/{repo}/blobs/sha256:{hexd}",
                        "-o", p], check=True)
    return p

cfg_hash = nixhash(fetch_hex(cfg))
layer_hashes = [nixhash(fetch_hex(h)) for h in layerdigs]

lines = [
    "# GENERATED by regenerate.sh — do not hand-edit.",
    "{ fetchers }:",
    "",
    "fetchers.fetchdocker {",
    f'  name = "halogen-flash-server";',
    '  registry = "https://ghcr.io/v2/";',
    f'  repository = "{repo.split("/")[0]}";',
    f'  imageName = "{repo.split("/")[1]}";',
    f'  tag = "{tag}";',
    "  imageConfig = fetchers.fetchDockerConfig {",
    '    registry = "https://ghcr.io/v2/";',
    f'    repository = "{repo.split("/")[0]}";',
    f'    imageName = "{repo.split("/")[1]}";',
    f'    tag = "{tag}";',
    f'    configDigest = "{cfg}";',
    f'    sha256 = "{cfg_hash}";',
    "  };",
    "  imageLayers = [",
]
for h, sh in zip(layerdigs, layer_hashes):
    lines += [
        "    (fetchers.fetchDockerLayer {",
        '      registry = "https://ghcr.io/v2/";',
        f'      repository = "{repo.split("/")[0]}";',
        f'      imageName = "{repo.split("/")[1]}";',
        f'      tag = "{tag}";',
        f'      layerDigest = "sha256:{h}";',
        f'      sha256 = "{sh}";',
        "    })",
    ]
lines += ["  ];", "}"]

new = "\n".join(lines) + "\n"
if check == "1":
    if os.path.exists(out) and open(out).read() == new:
        print(f"regenerate: nix/image.nix already matches {repo}:{tag}")
    else:
        sys.exit(f"regenerate: pin is stale for {repo}:{tag}; run regenerate.sh")
else:
    with open(out, "w") as f:
        f.write(new)
    print(f"regenerate: wrote {out} for {repo}:{tag} ({len(layerdigs)} layers)")
PY